backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/images
public_folder: /images

collections:
  - name: "Home Uk" 
    label: "Funnel"
    create: true
    files:
      - label: "Uk"
        name: "Uk"
        file: "content/uk/header.json"
        fields:
          - {label: "Logo", name: "logo", widget: image}
          - label: List
            name: list
            widget: list
            fields:
              - {label: "List Name", name: "item", widget: string}
              - {label: "List Image", name: "src", widget: image}
      - label: "Uk Content"
        name: "Uk Conetnt"
        file: "content/uk/content.json"
        fields:
          - {label: "Title", name: "title", widget: string} 
          - {label: "SUB Title", name: "subTitle", widget: string} 
          - {label: "Teser Img", name: "teaserImage", widget: image} 
          - {label: "Form img", name: "dataImage", widget: image} 
          - {label: "Thanks", name: "dataThanks", widget: string} 
          - {label: "Form Name", name: "dataName", widget: string} 
          - {label: "Form Phone", name: "dataPhone", widget: string} 
          - {label: "Data Button", name: "dataButton", widget: string} 
          - {label: "About Img", name: "aboutImage", widget: image} 
          - {label: "About Titile", name: "aboutTitile", widget: string}
          - {label: "About Text", name: "aboutText", widget: string}
          - {label: "About TExt Strong", name: "aboutTExtStrong", widget: string}
          - {label: "About Text Bottom", name: "aboutTextBottom", widget: string} 
          - label: Gallery About
            name: galleryAbout
            widget: list
            fields: 
              - {label: "List Image", name: "img", widget: image}
          - {label: "Contact Titile", name: "contactTitile", widget: string} 
          - {label: "Contact Name1", name: "contactName1", widget: string} 
          - {label: "Contact Phone1", name: "contactPhone1", widget: string} 
          - label: Contact Soz1
            name: contactSoz1
            widget: list
            fields: 
              - {label: "List Link", name: "src", widget: string}
              - {label: "List Image", name: "img", widget: image}
          - {label: "Contact Name2", name: "contactName2", widget: string} 
          - {label: "Contact Phone2", name: "contactPhone2", widget: string} 
          - label: Contact Soz2
            name: contactSoz2
            widget: list
            fields: 
              - {label: "List Link", name: "src", widget: string}
              - {label: "List Image", name: "img", widget: image}
          - label: Contact Footer Soc
            name: contactSozFooter
            widget: list
            fields: 
              - {label: "List Link", name: "src", widget: string}
              - {label: "List Image", name: "img", widget: image}
          - {label: "Map Image", name: "mapImage", widget: image} 
          - {label: "Map Width", name: "mapWidth", widget: string} 
          - {label: "Map Height", name: "mapHeight", widget: string} 
          - {label: "Footer Text", name: "footerText", widget: string} 
          - label: Comments
            name: items
            widget: list
            fields: 
              - {label: "Number", name: "value", widget: string} 
              - {label: "Title", name: "title", widget: string}
              - {label: "Img", name: "img", widget: image}
              - {label: "Paragraph", name: "paragraph", widget: string}
          - {label: "Seo Title", name: "seoTitle", widget: string} 
          - {label: "Seo Description", name: "seoDescription", widget: string} 
          - {label: "Seo Keywords", name: "seoKeywords", widget: string} 
   
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
